# Generated by Django 5.2.17 on 2026-09-27 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('kind', models.CharField(choices=[('RECEIPT', 'Risiti ya malipo'), ('REMINDER', 'Kikumbusho'), ('DISBURSED', 'Mkopo umetolewa'), ('GENERAL', 'Nyingine')], default='GENERAL', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Inasubiri'), ('SENT', 'Imetumwa'), ('FAILED', 'Imeshindwa'), ('SKIPPED', 'SMS zimezimwa')], default='PENDING', max_length=10)),
                ('response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer')),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='loans.loan')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SMS',
                'verbose_name_plural': 'SMS',
                'ordering': ['-created_at'],
            },
        ),
    ]
