# Generated by Django 5.2.17 on 2026-09-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Jina la tawi')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Mahali')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Simu')),
                ('is_active', models.BooleanField(default=True, verbose_name='Linafanya kazi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tawi',
                'verbose_name_plural': 'Matawi',
                'ordering': ['name'],
            },
        ),
    ]
