# Generated by Django 5.2.17 on 2026-09-27 16:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('CAPITAL_IN', 'Pesa zilizoongezwa'), ('FORM_FEE', 'Ada ya fomu'), ('VISIT_FEE', 'Ada ya kutembelea'), ('OTHER_INCOME', 'Mapato mengine'), ('EXPENSE', 'Matumizi'), ('TO_BANK', 'Pesa kwenda benki')], max_length=15, verbose_name='Aina')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Kiasi')),
                ('description', models.TextField(blank=True, verbose_name='Maelezo')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Tarehe')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_entries', to='core.branch', verbose_name='Tawi')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer', verbose_name='Mteja')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Muamala wa fedha',
                'verbose_name_plural': 'Daftari la fedha',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['branch', 'date', 'entry_type'], name='finance_cas_branch__f7aab5_idx')],
            },
        ),
    ]
