# Generated by Django 5.2.17 on 2026-09-27 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60, verbose_name='Jina la kwanza')),
                ('middle_name', models.CharField(blank=True, max_length=60, verbose_name='Jina la kati')),
                ('last_name', models.CharField(max_length=60, verbose_name='Jina la mwisho')),
                ('gender', models.CharField(choices=[('F', 'Mwanamke'), ('M', 'Mwanaume')], max_length=1, verbose_name='Jinsia')),
                ('phone', models.CharField(error_messages={'unique': 'Kuna mteja mwingine mwenye namba hii.'}, max_length=20, unique=True, verbose_name='Simu')),
                ('national_id', models.CharField(blank=True, max_length=30, verbose_name='Namba ya NIDA')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Makazi')),
                ('occupation', models.CharField(blank=True, max_length=120, verbose_name='Kazi au biashara')),
                ('guarantor_name', models.CharField(blank=True, max_length=120, verbose_name='Jina la mdhamini')),
                ('guarantor_phone', models.CharField(blank=True, max_length=20, verbose_name='Simu ya mdhamini')),
                ('guarantor_relation', models.CharField(blank=True, max_length=60, verbose_name='Uhusiano na mdhamini')),
                ('is_active', models.BooleanField(default=True, verbose_name='Yuko hai')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='core.branch', verbose_name='Tawi')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mteja',
                'verbose_name_plural': 'Wateja',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['branch', 'created_at'], name='customers_c_branch__5b4b6b_idx')],
            },
        ),
    ]
