# Generated by Django 5.2.17 on 2026-09-27 16:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Jina')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Riba (%)')),
                ('duration_days', models.PositiveIntegerField(default=30, verbose_name='Muda (siku)')),
                ('repayment_frequency', models.CharField(choices=[('DAILY', 'Kila siku'), ('WEEKLY', 'Kila wiki'), ('MONTHLY', 'Kila mwezi'), ('ONCE', 'Mara moja mwisho wa muda')], default='DAILY', max_length=10, verbose_name='Marejesho')),
                ('form_fee', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Ada ya fomu')),
                ('penalty_per_day', models.DecimalField(decimal_places=2, default=0, help_text='0 = hakuna faini ya moja kwa moja', max_digits=14, verbose_name='Faini kwa kila siku ya kuchelewa')),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Kiwango cha chini')),
                ('max_amount', models.DecimalField(decimal_places=2, default=0, help_text='0 = hakuna kikomo', max_digits=14, verbose_name='Kiwango cha juu')),
                ('is_active', models.BooleanField(default=True, verbose_name='Inatumika')),
            ],
            options={
                'verbose_name': 'Aina ya mkopo',
                'verbose_name_plural': 'Aina za mikopo',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Kiasi cha mkopo')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('interest_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_payable', models.DecimalField(decimal_places=2, max_digits=14)),
                ('duration_days', models.PositiveIntegerField()),
                ('repayment_frequency', models.CharField(choices=[('DAILY', 'Kila siku'), ('WEEKLY', 'Kila wiki'), ('MONTHLY', 'Kila mwezi'), ('ONCE', 'Mara moja mwisho wa muda')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Inasubiri kuthibitishwa'), ('APPROVED', 'Imethibitishwa'), ('ACTIVE', 'Anadaiwa'), ('COMPLETED', 'Amemaliza'), ('REJECTED', 'Imekataliwa'), ('WRITTEN_OFF', 'Imefutwa')], default='PENDING', max_length=12)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, verbose_name='Maelezo')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_loans', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='core.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_loans', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='customers.customer', verbose_name='Mteja')),
                ('disbursed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disbursed_loans', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loans.loanproduct', verbose_name='Aina ya mkopo')),
            ],
            options={
                'verbose_name': 'Mkopo',
                'verbose_name_plural': 'Mikopo',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Kiasi')),
                ('reason', models.CharField(default='Kuchelewa kulipa', max_length=200, verbose_name='Sababu')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('is_auto', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='penalty_entries', to='loans.loan')),
            ],
            options={
                'verbose_name': 'Faini',
                'verbose_name_plural': 'Faini',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Repayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Kiasi')),
                ('method', models.CharField(choices=[('CASH', 'Taslimu'), ('MPESA', 'M-Pesa'), ('MIXX', 'Mixx by Yas (Tigo Pesa)'), ('AIRTEL', 'Airtel Money'), ('HALOPESA', 'HaloPesa'), ('BANK', 'Benki')], default='CASH', max_length=10, verbose_name='Njia ya malipo')),
                ('reference', models.CharField(blank=True, max_length=60, verbose_name='Namba ya muamala')),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Maelezo')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repayments', to='loans.loan')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rejesho',
                'verbose_name_plural': 'Marejesho',
                'ordering': ['-paid_at'],
            },
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['status', 'due_date'], name='loans_loan_status_196efd_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['branch', 'status'], name='loans_loan_branch__294559_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['disbursed_at'], name='loans_loan_disburs_361763_idx'),
        ),
        migrations.AddConstraint(
            model_name='penalty',
            constraint=models.UniqueConstraint(condition=models.Q(('is_auto', True)), fields=('loan', 'date'), name='one_auto_penalty_per_day'),
        ),
        migrations.AddIndex(
            model_name='repayment',
            index=models.Index(fields=['paid_at'], name='loans_repay_paid_at_2c4796_idx'),
        ),
    ]
